#!/bin/bash

# Stop and remove all containers named 'hestia'
local_container_ids=$(docker ps -aq --filter name=hestia)

if [ -n "$local_container_ids" ]; then
    echo "Stopping and removing containers named 'hestia'..."
    docker stop $local_container_ids
    docker rm $local_container_ids
else
    echo "No containers named 'hestia' to stop or remove."
fi

# Remove all images named 'hestia'
local_image_ids=$(docker images -aq --filter reference=hestia)

if [ -n "$local_image_ids" ]; then
    echo "Removing docker images named 'hestia'..."
    docker rmi -f $local_image_ids
else
    echo "No Docker images named 'hestia' to remove."
fi
